### ISSUE TITLE
Model compatibility.

### ISSUE THREAD

**Issue by ImBadAtNames2019** [showlab/Tune-A-Video#20]
I tried like 4 different sd models and none of them worked, but it works with the standard sd 1.4 model. Any help? How can i use different sd custom models?

**Comment by ImBadAtNames2019** [comment]
This is the error that i keep getting, im using the colab notebook: 

2023-02-12 14:42:00.674440: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-02-12 14:42:02.544506: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64-nvidia
2023-02-12 14:42:02.544678: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64-nvidia
2023-02-12 14:42:02.544702: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
WARNING:accelerate.commands.launch:The following values were not passed to `accelerate launch` and had defaults used instead:
	`--num_processes` was set to a value of `1`
	`--num_machines` was set to a value of `1`
	`--mixed_precision` was set to a value of `'no'`
	`--dynamo_backend` was set to a value of `'no'`
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
2023-02-12 14:42:08.714047: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64-nvidia
2023-02-12 14:42:08.714176: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64-nvidia
2023-02-12 14:42:08.714201: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
INFO:__main__:Distributed environment: NO
Num processes: 1
Process index: 0
Local process index: 0
Device: cuda
Mixed precision type: fp16

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/diffusers/configuration_utils.py", line 380, in load_config
    config_dict = cls._dict_from_json_file(config_file)
  File "/usr/local/lib/python3.8/dist-packages/diffusers/configuration_utils.py", line 480, in _dict_from_json_file
    text = reader.read()
  File "/usr/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 64: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train_tuneavideo.py", line 352, in <module>
    main(**OmegaConf.load(args.config))
  File "train_tuneavideo.py", line 103, in main
    noise_scheduler = DDPMScheduler.from_pretrained(pretrained_model_path, subfolder="scheduler")
  File "/usr/local/lib/python3.8/dist-packages/diffusers/schedulers/scheduling_utils.py", line 118, in from_pretrained
    config, kwargs = cls.load_config(
  File "/usr/local/lib/python3.8/dist-packages/diffusers/configuration_utils.py", line 382, in load_config
    raise EnvironmentError(f"It looks like the config file at '{config_file}' is not a valid JSON file.")
OSError: It looks like the config file at '/content/drive/MyDrive/Stock Models that work with dreambooth/yohan-diffusion.ckpt' is not a valid JSON file.
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/launch.py", line 1097, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/launch.py", line 552, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', 'train_tuneavideo.py', '--config=configs/man-surfing.yaml']' returned non-zero exit status 1.

**Comment by zhangjiewu** [comment]
> I tried like 4 different sd models and none of them worked, but it works with the standard sd 1.4 model. Any help? How can i use different sd custom models?

We have tested on [Modern Disney](https://huggingface.co/nitrosocke/mo-di-diffusion) and [Redshift](https://huggingface.co/nitrosocke/redshift-diffusion). They work well.

**Comment by ImBadAtNames2019** [comment]
> 



> > I tried like 4 different sd models and none of them worked, but it works with the standard sd 1.4 model. Any help? How can i use different sd custom models?
> 
> We have tested on [Modern Disney](https://huggingface.co/nitrosocke/mo-di-diffusion) and [Redshift](https://huggingface.co/nitrosocke/redshift-diffusion). They work well.

At this point i tried like 8 different custom models and none worked, i keep getting the same error, any suggestions?

**Comment by zhangjiewu** [comment]
> dreambooth/yohan-diffusion.ckpt' is not a valid JSON file.

there might be some problem in your pretrained model.

**Comment by ImBadAtNames2019** [comment]
> > dreambooth/yohan-diffusion.ckpt' is not a valid JSON file.
> 
> there might be some problem in your pretrained model.

well i will test some more, i dont know what else to do, thanks anyways,

**Comment by raycrainiii** [comment]
hey can anyone source a good installation tutorial? i cant find anything except 1 video by that dude rodent on YT but he doesnt explain the install process... i want to use this model BADLY BUT I AM CLUELESS HOW TO DO IT plz help me thatnks guys for making this very cool
