### ISSUE TITLE
Error no file named scheduler_config.json found

### ISSUE THREAD

**Issue by mzolfaghari** [showlab/Tune-A-Video#30]
I downloaded stable-diffusion-v1-4 checkpoints "sd-v1-4-full-ema.ckpt", "sd-v1-4.ckpt" and put them into folder "./checkpoints/stable-diffusion-v1-4"! However when I run the `accelerate launch train_tuneavideo.py --config="configs/man-skiing.yaml"` I get the following error: 

`Traceback (most recent call last):
  File "/home/ubuntu/project/Tune-A-Video/train_tuneavideo.py", line 367, in <module>
    main(**OmegaConf.load(args.config))
  File "/home/ubuntu/project/Tune-A-Video/train_tuneavideo.py", line 105, in main
    noise_scheduler = DDPMScheduler.from_pretrained(pretrained_model_path, subfolder="scheduler")
  File "/opt/conda/envs/makevideo/lib/python3.9/site-packages/diffusers/schedulers/scheduling_utils.py", line 118, in from_pretrained
    config, kwargs = cls.load_config(
  File "/opt/conda/envs/makevideo/lib/python3.9/site-packages/diffusers/configuration_utils.py", line 320, in load_config
    raise EnvironmentError(
OSError: Error no file named scheduler_config.json found in directory ./checkpoints/stable-diffusion-v1-4.
Traceback (most recent call last):
  File "/opt/conda/envs/makevideo/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/envs/makevideo/lib/python3.9/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/opt/conda/envs/makevideo/lib/python3.9/site-packages/accelerate/commands/launch.py", line 915, in launch_command
    simple_launcher(args)
  File "/opt/conda/envs/makevideo/lib/python3.9/site-packages/accelerate/commands/launch.py", line 578, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/opt/conda/envs/makevideo/bin/python3.9', 'train_tuneavideo.py', '--config=configs/man-skiing.yaml']' returned non-zero exit status 1.`

Where can I get scheduler_config.json?

**Comment by mzolfaghari** [comment]
Ok seems that we should download all files from the stable-diffusion repo and put them in `./checkpoints/stable-diffusion-v1-4`. Here is the path to the files and models:
https://huggingface.co/CompVis/stable-diffusion-v1-4/tree/main

**Comment by kilickaya** [comment]
Is there a simple way to download all files under this directory, please?
