### ISSUE TITLE
在windows安装环境后，训练出现错误！

### ISSUE THREAD

**Issue by smartOf360** [showlab/Tune-A-Video#49]
环境如下：win10 python3.10.10

Package                 Version
----------------------- ---------
absl-py                 1.4.0    
accelerate              0.18.0   
antlr4-python3-runtime  4.9.3    
bitsandbytes            0.35.4   
brotlipy                0.7.0    
cachetools              5.3.0    
certifi                 2022.12.7
cffi                    1.15.1   
chardet                 5.1.0    
charset-normalizer      3.1.0    
colorama                0.4.6    
cryptography            39.0.1   
decord                  0.6.0
diffusers               0.11.1
einops                  0.6.0
filelock                3.10.7
flit_core               3.8.0
ftfy                    6.1.1
google-auth             2.17.1
google-auth-oauthlib    1.0.0
grpcio                  1.53.0
huggingface-hub         0.13.3
idna                    3.4
imageio                 2.27.0
importlib-metadata      6.1.0
Jinja2                  3.1.2
Markdown                3.4.3
MarkupSafe              2.1.2
mkl-fft                 1.3.1
mkl-random              1.2.2
mkl-service             2.4.0
modelcards              0.1.6
mpmath                  1.3.0
mypy-extensions         1.0.0
networkx                3.0
numpy                   1.24.2
oauthlib                3.2.2
omegaconf               2.3.0
packaging               23.0
Pillow                  9.5.0
pip                     23.0.1
protobuf                4.22.1
psutil                  5.9.4
pyasn1                  0.4.8
pyasn1-modules          0.2.8
pycparser               2.21
pyOpenSSL               23.0.0
pyre-extensions         0.0.23
PySocks                 1.7.1
PyYAML                  6.0
regex                   2023.3.23
requests                2.28.2
requests-oauthlib       1.3.1
rsa                     4.9
setuptools              65.6.3
six                     1.16.0
sympy                   1.11.1
tensorboard             2.12.1
tensorboard-data-server 0.7.0
tensorboard-plugin-wit  1.8.1
tokenizers              0.13.2
torch                   2.0.0
torchaudio              0.12.1
torchvision             0.13.1
tqdm                    4.65.0
transformers            4.27.4
typing_extensions       4.5.0
typing-inspect          0.8.0
urllib3                 1.26.15
wcwidth                 0.2.6
Werkzeug                2.2.3
wheel                   0.38.4
win-inet-pton           1.1.0
wincertstore            0.2
xformers                0.0.18
zipp                    3.15.0

个人怀疑是xFormers的兼容问题，但我用conda install xformers -c xformers安装不上，只能用pip进行安装，能否告知python的环境要求和xFormers的安装版本要求

显示如下警告和错误： 
WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.0.0+cu118 with CUDA 1108 (you have 2.0.0+cpu)
    Python  3.10.10 (you have 3.10.10)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
  Set XFORMERS_MORE_DETAILS=1 for more details
C:\Users\liugang\.conda\envs\t2video\lib\site-packages\torchvision\io\image.py:13: UserWarning: Failed to load image Python extension: Could not find module 'C:\Users\liugang\.conda\envs\t2video\Lib\site-packages\torchvision\image.pyd' (or one of its dependencies). Try using the full path with constructor syntax.
  warn(f"Failed to load image Python extension: {e}")
04/03/2023 23:54:32 - INFO - __main__ - Distributed environment: NO
Num processes: 1
Process index: 0
Local process index: 0
Device: cpu

Mixed precision type: fp16

{'variance_type', 'prediction_type'} was not found in config. Values will be initialized to default values.
{'num_class_embeds', 'dual_cross_attention', 'mid_block_type', 'resnet_time_scale_shift', 'use_linear_projection', 'class_embed_type', 'upcast_attention', 'only_cross_attention'} was not found in config. Values will be initialized to default values.
Traceback (most recent call last):
  File "D:\src\Tune-A-Video\train_tuneavideo.py", line 367, in <module>
    main(**OmegaConf.load(args.config))
  File "D:\src\Tune-A-Video\train_tuneavideo.py", line 123, in main
    unet.enable_xformers_memory_efficient_attention()
  File "C:\Users\liugang\.conda\envs\t2video\lib\site-packages\diffusers\modeling_utils.py", line 215, in enable_xformers_memory_efficient_attention
    self.set_use_memory_efficient_attention_xformers(True)
  File "C:\Users\liugang\.conda\envs\t2video\lib\site-packages\diffusers\modeling_utils.py", line 203, in set_use_memory_efficient_attention_xformers
    fn_recursive_set_mem_eff(module)
  File "C:\Users\liugang\.conda\envs\t2video\lib\site-packages\diffusers\modeling_utils.py", line 199, in fn_recursive_set_mem_eff
    fn_recursive_set_mem_eff(child)
  File "C:\Users\liugang\.conda\envs\t2video\lib\site-packages\diffusers\modeling_utils.py", line 199, in fn_recursive_set_mem_eff
    fn_recursive_set_mem_eff(child)
  File "C:\Users\liugang\.conda\envs\t2video\lib\site-packages\diffusers\modeling_utils.py", line 199, in fn_recursive_set_mem_eff
    fn_recursive_set_mem_eff(child)
  File "C:\Users\liugang\.conda\envs\t2video\lib\site-packages\diffusers\modeling_utils.py", line 196, in fn_recursive_set_mem_eff
    module.set_use_memory_efficient_attention_xformers(valid)
  File "C:\Users\liugang\.conda\envs\t2video\lib\site-packages\diffusers\modeling_utils.py", line 203, in set_use_memory_efficient_attention_xformers
    fn_recursive_set_mem_eff(module)
  File "C:\Users\liugang\.conda\envs\t2video\lib\site-packages\diffusers\modeling_utils.py", line 199, in fn_recursive_set_mem_eff
    fn_recursive_set_mem_eff(child)
  File "C:\Users\liugang\.conda\envs\t2video\lib\site-packages\diffusers\modeling_utils.py", line 196, in fn_recursive_set_mem_eff
    module.set_use_memory_efficient_attention_xformers(valid)
  File "D:\src\Tune-A-Video\tuneavideo\models\attention.py", line 213, in set_use_memory_efficient_attention_xformers
    raise ValueError(
ValueError: torch.cuda.is_available() should be True but is False. xformers' memory efficient attention is only available for GPU
Traceback (most recent call last):
  File "C:\Users\liugang\.conda\envs\t2video\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\liugang\.conda\envs\t2video\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\liugang\.conda\envs\t2video\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "C:\Users\liugang\.conda\envs\t2video\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "C:\Users\liugang\.conda\envs\t2video\lib\site-packages\accelerate\commands\launch.py", line 923, in launch_command
    simple_launcher(args)
  File "C:\Users\liugang\.conda\envs\t2video\lib\site-packages\accelerate\commands\launch.py", line 579, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\liugang\\.conda\\envs\\t2video\\python.exe', 'train_tuneavideo.py', '--config=configs/man-skiing.yaml']' returned non-zero exit status 1.

**Comment by zhangjiewu** [comment]
> 个人怀疑是xFormers的兼容问题，但我用conda install xformers -c xformers安装不上，只能用pip进行安装，能否告知python的环境要求和xFormers的安装版本要求

python版本为3.10.6，xformers版本为0.0.15或0.0.16。
