### ISSUE TITLE
help，请问这个怎么解决？

### ISSUE THREAD

**Issue by novazhjun** [showlab/Tune-A-Video#51]
(video) D:\pythonProject\video>accelerate launch train_tuneavideo.py --config="configs/man-skiing.yaml"
The following values were not passed to `accelerate launch` and had defaults used instead:
        `--num_processes` was set to a value of `0`
        `--num_machines` was set to a value of `1`
        `--mixed_precision` was set to a value of `'no'`
        `--dynamo_backend` was set to a value of `'no'`
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
04/11/2023 13:50:51 - INFO - __main__ - Distributed environment: NO
Num processes: 1
Process index: 0
Local process index: 0
Device: cpu

Mixed precision type: fp16

Traceback (most recent call last):
  File "C:\Users\YFT-IT-002\anaconda3\envs\video\lib\site-packages\diffusers\configuration_utils.py", line 326, in load_config
    config_file = hf_hub_download(
  File "C:\Users\YFT-IT-002\anaconda3\envs\video\lib\site-packages\huggingface_hub\utils\_validators.py", line 112, in _inner_fn
    validate_repo_id(arg_value)
  File "C:\Users\YFT-IT-002\anaconda3\envs\video\lib\site-packages\huggingface_hub\utils\_validators.py", line 160, in validate_repo_id
    raise HFValidationError(
huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': './checkpoints/stable-diffusion-v1-4'. Use `repo_type` argument if n
eeded.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train_tuneavideo.py", line 367, in <module>
    main(**OmegaConf.load(args.config))
  File "train_tuneavideo.py", line 105, in main
    noise_scheduler = DDPMScheduler.from_pretrained(pretrained_model_path, subfolder="scheduler")
  File "C:\Users\YFT-IT-002\anaconda3\envs\video\lib\site-packages\diffusers\schedulers\scheduling_utils.py", line 118, in from_pretrained
    config, kwargs = cls.load_config(
  File "C:\Users\YFT-IT-002\anaconda3\envs\video\lib\site-packages\diffusers\configuration_utils.py", line 363, in load_config
    raise EnvironmentError(
OSError: We couldn't connect to 'https://huggingface.co' to load this model, couldn't find it in the cached files and it looks like ./checkpoints/stable-diffusion-v1-4 is not the path to
a directory containing a scheduler_config.json file.
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/diffusers/installation#offline-mode'.
Traceback (most recent call last):
  File "C:\Users\YFT-IT-002\anaconda3\envs\video\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\YFT-IT-002\anaconda3\envs\video\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\YFT-IT-002\anaconda3\envs\video\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "C:\Users\YFT-IT-002\anaconda3\envs\video\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "C:\Users\YFT-IT-002\anaconda3\envs\video\lib\site-packages\accelerate\commands\launch.py", line 923, in launch_command
    simple_launcher(args)
  File "C:\Users\YFT-IT-002\anaconda3\envs\video\lib\site-packages\accelerate\commands\launch.py", line 579, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\YFT-IT-002\\anaconda3\\envs\\video\\python.exe', 'train_tuneavideo.py', '--config=configs/man-skiing.yaml']' returned non-zero exit st
atus 1.

**Comment by zhangjiewu** [comment]
你可以先把pretrained model (e.g., [stable-diffusion-v1-4](https://huggingface.co/CompVis/stable-diffusion-v1-4))下载到本地，并将config文件里的`pretrained_model_path`修改为相应路径。

**Comment by zhangtao22** [comment]
Cloning into 'checkpoints/CompVis/stable-diffusion-v1-4'...
remote: Enumerating objects: 738, done.
remote: Counting objects: 100% (12/12), done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 738 (delta 3), reused 12 (delta 3), pack-reused 726
Receiving objects: 100% (738/738), 682.52 KiB | 875.00 KiB/s, done.
Resolving deltas: 100% (123/123), done.
下边光标一直闪，不动是咋回事？用的autodl，是一直要等还是怎么？谢谢
