### ISSUE TITLE
The specified procedure could not be found.

### ISSUE THREAD

**Issue by 23Rj20** [showlab/Tune-A-Video#95]
After running the command: accelerate launch train_tuneavideo.py --config="configs/road-scenarios.yaml" on my own data
It shows this error:
Traceback (most recent call last):
  File "c:\Users\INP_Rohit\.conda\envs\phn\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\Users\INP_Rohit\.conda\envs\phn\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\INP_Rohit\.conda\envs\phn\Scripts\accelerate.exe\__main__.py", line 4, in <module>
  File "c:\Users\INP_Rohit\.conda\envs\phn\lib\site-packages\accelerate\__init__.py", line 3, in <module>
    from .accelerator import Accelerator
  File "c:\Users\INP_Rohit\.conda\envs\phn\lib\site-packages\accelerate\accelerator.py", line 32, in <module>
    import torch
  File "c:\Users\INP_Rohit\.conda\envs\phn\lib\site-packages\torch\__init__.py", line 129, in <module>
    raise err
OSError: [WinError 127] The specified procedure could not be found. Error loading "c:\Users\INP_Rohit\.conda\envs\phn\lib\site-packages\torch\lib\c10_cuda.dll" or one of its dependencies.

**Comment by 23Rj20** [comment]
the above error was clearecd after reinsatlling cuda again using torch

But a new error arrived when i run the command again:
The following values were not passed to `accelerate launch` and had defaults used instead:
        `--num_processes` was set to a value of `1`
        `--num_machines` was set to a value of `1`
        `--mixed_precision` was set to a value of `'no'`
        `--dynamo_backend` was set to a value of `'no'`
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
03/29/2024 11:28:57 - INFO - __main__ - Distributed environment: NO
Num processes: 1
Process index: 0
Local process index: 0
Device: cuda

Mixed precision type: fp16

Traceback (most recent call last):
  File "c:\Users\INP_Rohit\.conda\envs\phn\lib\site-packages\diffusers\configuration_utils.py", line 326, in load_config
    config_file = hf_hub_download(
  File "c:\Users\INP_Rohit\.conda\envs\phn\lib\site-packages\huggingface_hub\utils\_validators.py", line 110, in _inner_fn
    validate_repo_id(arg_value)
  File "c:\Users\INP_Rohit\.conda\envs\phn\lib\site-packages\huggingface_hub\utils\_validators.py", line 158, in validate_repo_id
    raise HFValidationError(
huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': './checkpoints/stable-diffusion-v1-4'. Use `repo_type` argument if needed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\INP_Rohit\Documents\ImageGeneration\Tune-A-Video\train_tuneavideo.py", line 367, in <module>
    main(**OmegaConf.load(args.config))
  File "C:\Users\INP_Rohit\Documents\ImageGeneration\Tune-A-Video\train_tuneavideo.py", line 105, in main
    noise_scheduler = DDPMScheduler.from_pretrained(pretrained_model_path, subfolder="scheduler")
  File "c:\Users\INP_Rohit\.conda\envs\phn\lib\site-packages\diffusers\schedulers\scheduling_utils.py", line 118, in from_pretrained
    config, kwargs = cls.load_config(
  File "c:\Users\INP_Rohit\.conda\envs\phn\lib\site-packages\diffusers\configuration_utils.py", line 363, in load_config
    raise EnvironmentError(
OSError: We couldn't connect to 'https://huggingface.co' to load this model, couldn't find it in the cached files and it looks like ./checkpoints/stable-diffusion-v1-4 is not the path to a directory containing a scheduler_config.json file.
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/diffusers/installation#offline-mode'.
Traceback (most recent call last):
  File "c:\Users\INP_Rohit\.conda\envs\phn\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\Users\INP_Rohit\.conda\envs\phn\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\INP_Rohit\.conda\envs\phn\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "c:\Users\INP_Rohit\.conda\envs\phn\lib\site-packages\accelerate\commands\accelerate_cli.py", line 47, in main
    args.func(args)
  File "c:\Users\INP_Rohit\.conda\envs\phn\lib\site-packages\accelerate\commands\launch.py", line 1023, in launch_command
    simple_launcher(args)
  File "c:\Users\INP_Rohit\.conda\envs\phn\lib\site-packages\accelerate\commands\launch.py", line 643, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['c:\\Users\\INP_Rohit\\.conda\\envs\\phn\\python.exe', 'train_tuneavideo.py', '--config=configs/road-scenarios.yaml']' returned non-zero exit status 1.

**Comment by shani1610** [comment]
@23Rj20 same for me, did you solve it?
